spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ragdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT:8080}

api:
  key: ${APP_API_KEY}
  key-header: X-API-KEY
  rate:
    limit: ${APP_RATE_LIMIT:100}

management:
  endpoints:
    web:
      exposure:
        include: health,info
